novdat.Name[argument0]="";
novdat.DName[argument0]="";
novdat.Version[argument0]=0;
novdat.Author[argument0]="";
novdat.Background[argument0]="";
if (argument1) {novdat.FolderName[argument0]="";}
novdat.Music[argument0]="";
novdat.MusicPreview[argument0]=0;
novdat.FName[argument0]="";
if (argument1) {novdat.FolName[argument0]="Novels\"+"";}
novdat.FileName[argument0]="";
novdat.isActive[argument0]=0;
novdat.scenario[argument0]="";
novdat.CustomMenu[argument0]="";
novdat.Color[argument0]=c_white;
novdat.OutColor[argument0]=c_black;
novdat.isObsolete[argument0]=0;
novdat.links[argument0]=ds_map_create();
novdat.linkstype[argument0]=ds_map_create();
novdat.fonts[argument0]=ds_map_create();

novdat.ScriptVersion[argument0]=2;
novdat.Creator[argument0]="";
novdat.StoryType[argument0]=-1;
novdat.Description[argument0]="";
novdat.HasMenu[argument0]=0;
novdat.GenreCount[argument0]=0;
novdat.Size[argument0]="";
novdat.HasViolence[argument0]=0;
novdat.HasNSFW[argument0]=0;
novdat.Folder[argument0]="";
novdat.ASCIIName[argument0]="";
novdat.RName[argument0]="";
novdat.Deleted[argument0]=0;
novdat.prefix[argument0]="";
